export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    PRODUCT_CATEGORIES: "PRODUCT_CATEGORIES",
    SELECTED_CATEGORY: "SELECTED_CATEGORY"
}